### ISSUE TITLE
Demonstrate event parsing from main-net

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/purescript-kitty-monitor#4]
We know that certain bugs (https://github.com/ethereum/go-ethereum/issues/15243) can prevent us from parsing events successfully. We have demonstrated that running a node on a more powerful server can at the least temporarily mitigate the issue.

Considering that we will want to replay events from the main-net, we will have to figure out a robust solution to this. This solution will later serve us as we deploy on the main-net ourselves.

- [ ] demonstrate long time event parsing off main-net

**Comment by iostat** [comment]
I'm gonna close this now that we have `parity-proxy.foam` w/ full archive node
